
export default [
    {upper: 'А', lower: 'а', latin: 'A' },
    {upper: 'Б', lower: 'б', latin: 'Be' },
    {upper: 'В', lower: 'в', latin: 'Ve' },
    {upper: 'Г', lower: 'г', latin: 'Ge' },
    {upper: 'Д', lower: 'б', latin: 'De' },
    {upper: 'Е', lower: 'е', latin: 'Ye' },
    {upper: 'Ё', lower: 'ё', latin: 'Yo' },
    {upper: 'Ж', lower: 'ж', latin: 'Zhe' },
    {upper: 'З', lower: 'з', latin: 'Ze' },
    {upper: 'И', lower: 'и', latin: 'I' },
    {upper: 'Й', lower: 'й', latin: 'Y' },
    {upper: 'К', lower: 'к', latin: 'Ka' },
    {upper: 'Л', lower: 'л', latin: 'El' },
    {upper: 'М', lower: 'м', latin: 'Em' },
    {upper: 'Н', lower: 'н', latin: 'En' },
    {upper: 'О', lower: 'о', latin: 'O' },
    {upper: 'П', lower: 'п', latin: 'Pe' },
    {upper: 'Р', lower: 'р', latin: 'Er' },
    {upper: 'С', lower: 'с', latin: 'Es' },
    {upper: 'Т', lower: 'т', latin: 'Te' },
    {upper: 'У', lower: 'у', latin: 'Ou' },
    {upper: 'Ф', lower: 'ф', latin: 'Ef' },
    {upper: 'Х', lower: 'х', latin: 'Kha' },
    {upper: 'Ц', lower: 'ц', latin: 'Tse' },
    {upper: 'Ч', lower: 'ч', latin: 'Che' },
    {upper: 'Ш', lower: 'ш', latin: 'Sha'},
    {upper: 'Щ', lower: 'щ', latin: 'Scha'},
    {upper: 'Ъ', lower: 'ъ', latin: 'Jer'},
    {upper: 'Ы', lower: 'ы', latin: ''},
    {upper: 'Ь', lower: 'ь', latin: ''},
    {upper: 'Э', lower: 'э', latin: 'é'},
    {upper: 'Ю', lower: 'ю', latin: 'Yu'},
    {upper: 'Я', lower: 'я', latin: 'Ya'},
]
